### ISSUE TITLE
ReferenceError: closesAt is not defined

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay-poll#1]
Triggered by the "best pizza type" poll.

```
ReferenceError: closesAt is not defined
    at printClosesAt (/home/christianbundy/src/ssbc/patchbay/node_modules/patchbay-poll/views/show.js:194:29)
    at PollShow (/home/christianbundy/src/ssbc/patchbay/node_modules/patchbay-poll/views/show.js:42:9)
    at Array.pollShowPage (/home/christianbundy/src/ssbc/patchbay/node_modules/patchbay-poll/modules/app/page/pollShow.js:26:12)
    at Array.<anonymous> (/home/christianbundy/src/ssbc/patchbay/node_modules/depject/apply.js:18:30)
    at Router (/home/christianbundy/src/ssbc/patchbay/router/async/router.js:34:33)
    at api.router.async.normalise (/home/christianbundy/src/ssbc/patchbay/router/async/router.js:21:7)
    at Object.normalise (/home/christianbundy/src/ssbc/patchbay/router/async/normalise.js:16:7)
    at Object.normalise (/home/christianbundy/src/ssbc/patchbay/node_modules/depject/apply.js:18:30)
    at Object.nest (/home/christianbundy/src/ssbc/patchbay/router/async/router.js:18:22)
    at Object.router (/home/christianbundy/src/ssbc/patchbay/node_modules/depject/apply.js:18:30)
    at api.router.async.normalise (/home/christianbundy/src/ssbc/patchbay/app/sync/goTo.js:52:24)
    at Object.normalise (/home/christianbundy/src/ssbc/patchbay/router/async/normalise.js:16:7)
    at Object.normalise (/home/christianbundy/src/ssbc/patchbay/node_modules/depject/apply.js:18:30)
    at goTo (/home/christianbundy/src/ssbc/patchbay/app/sync/goTo.js:34:22)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/depject/apply.js:18:30
    at HTMLDivElement.onClick (/home/christianbundy/src/ssbc/patchbay/node_modules/patchbay-poll/views/index.js:34:31)
```

**Comment by mixmix** [comment]
yeah this is an easy fix by the looks 
```js
function printClosesAt (dateTime) {
  const date = dateTime.toDateString()
  const [ _, time, zone ] = closesAt.toTimeString().match(/^(\d+:\d+).*(\([\w\s]+\))$/) // closesAt should be dateTime...
  return `${time}, ${date} ${zone}`
}
```

**Comment by mixmix** [comment]
fixed
